version: "3.9"
services:
  whatsapp-agent-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - PHONE_AGENT=${PHONE_AGENT}
